version: '2'
services:
  ekanban-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    ports:
     - "8080:8080"
    volumes:
     - ./backend:/usr/src/app
  ekanban-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
     - "80:3000"
    volumes:
     - ./frontend:/usr/src/app
