version: '2'
services:
  ekanban-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    ports:
     - "8080:8080"
    volumes:
     - ./backend:/usr/src/app
    depends_on:
     - ekanban-mongodb
  ekanban-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
     - "80:3000"
    volumes:
     - ./frontend:/usr/src/app
  ekanban-mongodb:
    build: mongodb/.
    environment:
     - MONGODB_USERNAME=ekanban
     - MONGODB_PASSWORD=nabnake
     - MONGODB_DBNAME=ekanban
    ports:
     - "27017:27017"
